version: "3.9"
networks:
  test-task-dev:
    driver: bridge
services:
  app: 
    container_name: test-task
    build:
      context: .
      dockerfile: aspnetcore.dockerfile
    ports:
      - "80:80"
    networks:
      - test-task-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test-task
    ports:
      - "5432:5432"
    networks:
      - test-task-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
volumes:
  postgres-data: