-- Table: public.City

-- DROP TABLE IF EXISTS public."City";

CREATE TABLE IF NOT EXISTS public."City"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 10 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CityName" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_City" PRIMARY KEY ("ID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."City"
    OWNER to postgres;



-- Table: public.Street

-- DROP TABLE IF EXISTS public."Street";

CREATE TABLE IF NOT EXISTS public."Street"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 50 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "StreetName" text COLLATE pg_catalog."default" NOT NULL,
    "CityID" integer NOT NULL,
    CONSTRAINT "PK_Street" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Street_City_CityID" FOREIGN KEY ("CityID")
        REFERENCES public."City" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Street"
    OWNER to postgres;
-- Index: IX_Street_CityID

-- DROP INDEX IF EXISTS public."IX_Street_CityID";

CREATE INDEX IF NOT EXISTS "IX_Street_CityID"
    ON public."Street" USING btree
    ("CityID" ASC NULLS LAST)
    TABLESPACE pg_default;



-- Table: public.House

-- DROP TABLE IF EXISTS public."House";

CREATE TABLE IF NOT EXISTS public."House"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 500 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "HouseName" text COLLATE pg_catalog."default" NOT NULL,
    "FlatsNumber" integer,
    "StreetID" integer NOT NULL,
    CONSTRAINT "PK_House" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_House_Street_StreetID" FOREIGN KEY ("StreetID")
        REFERENCES public."Street" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."House"
    OWNER to postgres;
-- Index: IX_House_StreetID

-- DROP INDEX IF EXISTS public."IX_House_StreetID";

CREATE INDEX IF NOT EXISTS "IX_House_StreetID"
    ON public."House" USING btree
    ("StreetID" ASC NULLS LAST)
    TABLESPACE pg_default;




-- Table: public.Flat

-- DROP TABLE IF EXISTS public."Flat";

CREATE TABLE IF NOT EXISTS public."Flat"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 500 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FlatName" text COLLATE pg_catalog."default" NOT NULL,
    "HouseID" integer NOT NULL,
    CONSTRAINT "PK_Flat" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Flat_House_HouseID" FOREIGN KEY ("HouseID")
        REFERENCES public."House" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Flat"
    OWNER to postgres;
-- Index: IX_Flat_HouseID

-- DROP INDEX IF EXISTS public."IX_Flat_HouseID";

CREATE INDEX IF NOT EXISTS "IX_Flat_HouseID"
    ON public."Flat" USING btree
    ("HouseID" ASC NULLS LAST)
    TABLESPACE pg_default;


-- Table: public.Owner

-- DROP TABLE IF EXISTS public."Owner";

CREATE TABLE IF NOT EXISTS public."Owner"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 500 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FIO" text COLLATE pg_catalog."default" NOT NULL,
    "FlatID" integer NOT NULL,
    CONSTRAINT "PK_Owner" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Owner_Flat_FlatID" FOREIGN KEY ("FlatID")
        REFERENCES public."Flat" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Owner"
    OWNER to postgres;
-- Index: IX_Owner_FlatID

-- DROP INDEX IF EXISTS public."IX_Owner_FlatID";

CREATE INDEX IF NOT EXISTS "IX_Owner_FlatID"
    ON public."Owner" USING btree
    ("FlatID" ASC NULLS LAST)
    TABLESPACE pg_default;